#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=20:00:00
#PBS -l mem=128GB
#PBS -N ogRGC
#PBS -M ek99@nyu.edu
#PBS -j oe

module load matlab/2016b

cd /scratch/ek99/JWLOrientedGabor/

# If the files you are running are not in the same folder as this script,
# you can insert "addpath(genpath('/PATH/TO/FILES/'));" before the command
# you want to run.
matlab -nodisplay -r "addpath(genpath('/scratch/ek99/JWLOrientedGabor')); addpath(genpath('/scratch/ek99/isetbio')); s_ogRGC; exit()"

exit

